# Generated by Django 4.2.6 on 2024-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="branch",
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ManyToManyField(to="company.branch"),
        ),
    ]
