# Generated by Django 4.2.6 on 2024-05-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
        ("users", "0002_remove_user_branch_user_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="branch",
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
            preserve_default=False,
        ),
    ]
