# Generated by Django 5.0.6 on 2024-08-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_branch_alter_user_company_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('sales', 'Salesperson'), ('accountant', 'Accountant')], max_length=50),
        ),
    ]
