# Generated by Django 5.0.6 on 2024-05-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_remove_company_user"),
        ("users", "0003_remove_user_branch_user_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
        ),
    ]
