# Generated by Django 5.0.6 on 2024-05-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="payment_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_stock_transactions",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="payment_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
