# Generated by Django 5.0.6 on 2024-07-30 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qoutation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
        migrations.AddField(
            model_name='qoutation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='qoutation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.customer'),
        ),
        migrations.AddField(
            model_name='qoutationitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='qoutationitems',
            name='qoute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoute_items', to='finance.qoutation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='payment_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_stock_transactions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customer'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.vatrate'),
        ),
        migrations.AddField(
            model_name='vattransaction',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='customeraccountbalances',
            unique_together={('account', 'currency')},
        ),
    ]
