# Generated by Django 5.0.6 on 2024-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
