# Generated by Django 5.0.6 on 2024-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_stocktransaction_payment_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5),
        ),
    ]
