# Generated by Django 5.0.6 on 2024-06-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vattransaction",
            name="stock_transaction",
        ),
        migrations.RemoveField(
            model_name="vattransaction",
            name="transaction",
        ),
        migrations.AddField(
            model_name="vattransaction",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
    ]
