# Generated by Django 5.0.6 on 2024-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
