# Generated by Django 5.0.6 on 2024-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_qoutationitems_qoute"),
    ]

    operations = [
        migrations.AddField(
            model_name="qoutation",
            name="products",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
    ]
