# Generated by Django 5.0.6 on 2024-05-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_vatrate_rate"),
        ("inventory", "0010_product_tax_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.product"
            ),
        ),
    ]
