# Generated by Django 5.0.6 on 2024-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_qoutationitems_qoute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbook",
            name="date",
            field=models.DateField(),
        ),
    ]
