# Generated by Django 5.0.6 on 2024-06-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_cashwithdraw"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashwithdraw",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
            preserve_default=False,
        ),
    ]
