# Generated by Django 4.2.16 on 2024-09-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_cashbook_accountant_cashbook_cancelled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashbook",
            name="sale",
        ),
        migrations.AddField(
            model_name="cashbook",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
            ),
        ),
    ]
