# Generated by Django 5.0.6 on 2024-07-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_purchaseorderaccount'),
        ('inventory', '0005_purchaseorder_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.purchaseorder')),
            ],
        ),
    ]
