# Generated by Django 5.0.6 on 2024-06-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_cashwithdraw_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashwithdraw",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
