# Generated by Django 5.0.6 on 2024-07-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_purchasesaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderaccount',
            name='expensed',
            field=models.BooleanField(default=False),
        ),
    ]
