# Generated by Django 5.0.6 on 2024-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_stocktransaction_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="vatrate",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
