# Generated by Django 5.0.6 on 2024-06-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_cashtransfers"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashtransfers",
            name="received_status",
            field=models.BooleanField(default=False),
        ),
    ]
