# Generated by Django 5.0.6 on 2024-05-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_vatrate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vattransaction",
            name="stock_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.stocktransaction",
            ),
        ),
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
