# Generated by Django 5.0.6 on 2024-07-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_cashwithdraw_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("credit card", "Credit Card"),
                    ("pay later", "pay later"),
                    ("Ecocash", "Ecocash"),
                ],
                max_length=50,
            ),
        ),
    ]
