# Generated by Django 4.2.16 on 2024-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_cashbooknote"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="note",
            field=models.TextField(default="", null=True),
        ),
    ]
