# Generated by Django 5.0.6 on 2024-06-13 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_alter_cashbook_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashbook",
            old_name="date",
            new_name="issue_date",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="date",
            new_name="issue_date",
        ),
    ]
