# Generated by Django 5.0.6 on 2024-07-31 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_purchaseorderaccount_expensed'),
        ('inventory', '0006_purchaseorder_discount_purchaseorder_handling_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderaccount',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.expense'),
        ),
        migrations.AddField(
            model_name='vattransaction',
            name='purchase_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder'),
        ),
    ]
