# Generated by Django 5.0.6 on 2024-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_return",
            field=models.BooleanField(default=False),
        ),
    ]
