# Generated by Django 4.2.16 on 2024-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_cashbook_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbook",
            name="credit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cashbook",
            name="debit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expense",
            name="issue_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
