# Generated by Django 5.0.6 on 2024-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_vattransaction_stock_transaction_alter_vatrate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vattransaction",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
