# Generated by Django 5.0.6 on 2024-08-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_purchaseorderaccount_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderaccount',
            name='expense',
        ),
    ]
