# Generated by Django 5.0.6 on 2024-05-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_alter_vattransaction_vat_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(),
        ),
    ]
