# Generated by Django 5.0.6 on 2024-07-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoice_invoice_return'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashwithdraw',
            old_name='user_code',
            new_name='password',
        ),
    ]
