# Generated by Django 5.0.6 on 2024-05-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
        ("finance", "0008_alter_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
            preserve_default=False,
        ),
    ]
