# Generated by Django 5.0.6 on 2024-07-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_user_code_cashwithdraw_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='recurring',
            new_name='reocurring',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recurrence_period',
            field=models.IntegerField(default=0),
        ),
    ]
