# Generated by Django 4.2.16 on 2024-09-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_salesreturns_cashdeposit_accounttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderaccount",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "cash"), ("bank", "bank"), ("ecocash", "ecocash")],
                default="cash",
                max_length=15,
            ),
        ),
    ]
