# Generated by Django 5.0.6 on 2024-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_recurring_invoice_reocurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountbalances',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('bank', 'bank'), ('ecocash', 'ecocash')], default='cash', max_length=15),
            preserve_default=False,
        ),
    ]
