# Generated by Django 5.0.6 on 2024-05-13 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="sale",
        ),
    ]
