# Generated by Django 5.0.6 on 2024-07-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_customeraccountbalances_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccountbalances',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='CustomerDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('bank', 'bank'), ('ecocash', 'ecocash')], default='cash', max_length=15)),
                ('reason', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_deposits', to='finance.customeraccountbalances')),
            ],
        ),
    ]
