# Generated by Django 4.2.16 on 2024-09-18 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_purchaseorderaccount_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderaccount",
            name="payment_method",
        ),
    ]
