# Generated by Django 4.2.16 on 2024-09-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_remove_purchaseorderaccount_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="cogsitems",
            name="cogs",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.cogs",
            ),
        ),
    ]
