# Generated by Django 5.0.6 on 2024-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_customeraccountbalances_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdeposits',
            old_name='balance',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='customerdeposits',
            name='payment_reference',
            field=models.CharField(default='cash-ref', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
