# Generated by Django 5.0.6 on 2024-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
