# Generated by Django 4.2.16 on 2024-09-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_cogsitems_cogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cogsitems",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 18, 15, 1, 41, 272492, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
