# Generated by Django 5.0.6 on 2024-05-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_invoice_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="vat_rate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.vatrate",
            ),
            preserve_default=False,
        ),
    ]
