# Generated by Django 5.0.6 on 2024-07-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_customerdeposits_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeposits',
            name='payment_reference',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
