# Generated by Django 4.2.16 on 2024-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_cashdeposit_currency_cashwithdrawals"),
    ]

    operations = [
        migrations.AddField(
            model_name="vattransaction",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
