# Generated by Django 5.0.6 on 2024-05-14 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_remove_sale_payment_method_invoiceitem_vat_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 14, 6, 36, 24, 93278, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
