# Generated by Django 5.0.6 on 2024-07-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('finance', '0015_alter_customerdeposits_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
    ]
