# Generated by Django 4.2.16 on 2024-09-19 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_vattransaction_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="vattransaction",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
