# Generated by Django 5.0.6 on 2024-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_receipt_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="discount_percentage",
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="date",
            field=models.DateField(),
        ),
    ]
