# Generated by Django 5.0.6 on 2024-07-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('finance', '0016_cashbook_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeposits',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
    ]
