# Generated by Django 5.0.6 on 2024-05-15 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_remove_invoiceitem_discount_percentage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="reference",
            new_name="reference_number",
        ),
    ]
