# Generated by Django 4.2.16 on 2024-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("cash", "cash"),
                    ("layby", "layby"),
                    ("installment", "installment"),
                ],
                default="cash",
            ),
            preserve_default=False,
        ),
    ]
