# Generated by Django 5.0.6 on 2024-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_customerdeposits_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
