# Generated by Django 5.0.6 on 2024-05-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_rename_reference_transaction_reference_number"),
        ("inventory", "0010_product_tax_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finance.invoice"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.inventory"
            ),
        ),
    ]
