# Generated by Django 4.2.16 on 2024-10-14 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_invoice_payment_terms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="next_due_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="recurrence_period",
        ),
    ]
