# Generated by Django 4.2.16 on 2024-10-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_remove_invoice_next_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
