# Generated by Django 5.0.6 on 2024-07-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_payment_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
    ]
