# Generated by Django 5.0.6 on 2024-07-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_remove_payment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
