# Generated by Django 4.2.16 on 2024-10-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_alter_invoice_delivery_charge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="note",
            field=models.TextField(null=True),
        ),
    ]
