# Generated by Django 5.0.6 on 2024-07-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_payment_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeposits',
            name='payment_reference',
            field=models.CharField(default='', max_length=255),
        ),
    ]
