# Generated by Django 5.0.6 on 2024-05-16 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_alter_stocktransaction_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id_number",
        ),
    ]
