# Generated by Django 5.0.6 on 2024-07-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('finance', '0022_alter_customerdeposits_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.branch'),
            preserve_default=False,
        ),
    ]
