# Generated by Django 4.2.16 on 2024-10-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0023_layby_recurringinvoices_laybydates"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="hold_status",
            field=models.BooleanField(default=False),
        ),
    ]
