# Generated by Django 5.0.6 on 2024-05-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0023_remove_customer_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(default="123", max_length=100),
            preserve_default=False,
        ),
    ]
