# Generated by Django 5.0.6 on 2024-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_customer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
