# Generated by Django 4.2.16 on 2024-10-20 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0024_invoice_hold_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountbalance",
            unique_together=set(),
        ),
    ]
