# Generated by Django 5.0.6 on 2024-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0024_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True),
        ),
    ]
