# Generated by Django 5.0.6 on 2024-05-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
        ("finance", "0025_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.branch",
            ),
        ),
    ]
