# Generated by Django 4.2.16 on 2024-10-21 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0025_alter_accountbalance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountbalance",
            unique_together={("account", "currency")},
        ),
    ]
