# Generated by Django 4.2.16 on 2024-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0027_alter_accountbalance_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_received",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
