# Generated by Django 5.0.6 on 2024-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0027_alter_invoiceitem_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
