# Generated by Django 5.0.6 on 2024-05-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0028_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="transaction",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="receipt",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="item",
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name="CustomerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.customer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PayLaterTransaction",
        ),
        migrations.DeleteModel(
            name="Receipt",
        ),
        migrations.DeleteModel(
            name="ReceiptItem",
        ),
    ]
