# Generated by Django 5.0.6 on 2024-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0030_invoice_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
