# Generated by Django 5.0.6 on 2024-05-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0031_invoice_amount_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.paymentmethod",
            ),
        ),
    ]
