# Generated by Django 5.0.6 on 2024-05-22 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0032_currency_exchange_rate_invoice_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 5, 22, 20, 22, 28, 53586, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
