# Generated by Django 5.0.6 on 2024-05-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0033_customer_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="delivery_charge",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="next_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurrence_period",
            field=models.IntegerField(default=29),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
    ]
