# Generated by Django 5.0.6 on 2024-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0035_remove_invoice_payment_method_payment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="discount_percentage",
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
