# Generated by Django 5.0.6 on 2024-05-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0036_remove_invoiceitem_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
