# Generated by Django 5.0.6 on 2024-05-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0038_expense_user_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
