# Generated by Django 5.0.6 on 2024-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0039_alter_stocktransaction_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="note",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="products_purchased",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
