# Generated by Django 5.0.6 on 2024-05-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0040_invoice_note_invoice_products_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="invoice",
            field=models.ForeignKey(
                default=102,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.invoice",
            ),
            preserve_default=False,
        ),
    ]
