# Generated by Django 5.0.6 on 2024-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0041_customer_id_number_stocktransaction_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateTimeField(),
        ),
    ]
