# Generated by Django 5.0.6 on 2024-05-30 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0042_alter_invoice_issue_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashaccount",
            name="balance",
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="finance.cashaccount",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.currency",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "currency")},
            },
        ),
    ]
