# Generated by Django 5.0.6 on 2024-05-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0043_remove_cashaccount_balance_accountbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("CA", "Cash"), ("BA", "Bank"), ("EC", "Ecocash")],
                        default="CA",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAccountBalances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BankAccount",
        ),
        migrations.RemoveField(
            model_name="customeraccount",
            name="balance",
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="customeraccountbalances",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="finance.customeraccount",
            ),
        ),
        migrations.AddField(
            model_name="customeraccountbalances",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.currency"
            ),
        ),
        migrations.DeleteModel(
            name="CashAccount",
        ),
        migrations.AlterUniqueTogether(
            name="customeraccountbalances",
            unique_together={("account", "currency")},
        ),
    ]
