# Generated by Django 5.0.6 on 2024-05-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_remove_company_user"),
        ("finance", "0044_account_customeraccountbalances_delete_bankaccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountbalance",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
            preserve_default=False,
        ),
    ]
