# Generated by Django 5.0.6 on 2024-05-30 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0046_customeraccountbalances_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeraccountbalances",
            name="branch",
        ),
    ]
