# Generated by Django 5.0.6 on 2024-05-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0047_remove_customeraccountbalances_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
