# Generated by Django 5.0.6 on 2024-05-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0048_expense_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "cash"), ("bank", "bank"), ("ecocash", "ecocash")],
                default="cash",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
