# Generated by Django 5.0.6 on 2024-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0049_expense_currency_expense_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
