# Generated by Django 5.0.6 on 2024-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_printer_mac_address_printer_system_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationssettings',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
