# Generated by Django 5.0.6 on 2024-08-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_notificationssettings_low_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationssettings',
            name='transfer_receiving',
            field=models.BooleanField(default=True),
        ),
    ]
