# Generated by Django 5.0.6 on 2024-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_notificationssettings_transfer_receiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationssettings',
            name='cash_deposits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationssettings',
            name='cash_withdrawal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationssettings',
            name='money_transfer',
            field=models.BooleanField(default=True),
        ),
    ]
