# Generated by Django 5.0.6 on 2024-08-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_notificationssettings_cash_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationssettings',
            name='recurring_invoices',
            field=models.BooleanField(default=True),
        ),
    ]
