# Generated by Django 5.0.6 on 2024-07-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
