# Generated by Django 5.0.6 on 2024-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="over_less",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "stock in"),
                    ("Stock update", "Stock update"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                ],
                max_length=20,
            ),
        ),
    ]
