# Generated by Django 5.0.6 on 2024-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
