# Generated by Django 5.0.6 on 2024-06-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cashbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.CharField(max_length=255)),
                ("debit", models.BooleanField(default=True)),
                ("credit", models.BooleanField(default=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "Stock in"),
                    ("Stock update", "Stock update"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                ],
                max_length=20,
            ),
        ),
    ]
