# Generated by Django 5.0.6 on 2024-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_transferitems_over_less_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="over_less_quantity",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
