# Generated by Django 5.0.6 on 2024-06-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_transferitems_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="over_less_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
