# Generated by Django 5.0.6 on 2024-06-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_activitylog_product_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknotifications",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.transferitems",
            ),
        ),
        migrations.AlterField(
            model_name="stocknotifications",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="stocknotifications",
            name="type",
            field=models.CharField(
                choices=[
                    ("stock level", "Stock level"),
                    ("stock take", "stock take"),
                    ("stock transfer", "stock transfer"),
                ],
                max_length=30,
            ),
        ),
    ]
