# Generated by Django 4.2.6 on 2024-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventory_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
