# Generated by Django 5.0.6 on 2024-06-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0002_activitylog_product_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_branch', to='company.branch'),
            preserve_default=False,
        ),
    ]
