# Generated by Django 5.0.6 on 2024-07-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact',
            new_name='contact_name',
        ),
    ]
