# Generated by Django 4.2.16 on 2024-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_purchaseorder_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
            ],
        ),
    ]
