# Generated by Django 5.0.6 on 2024-06-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_transferitems_over_less_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "stock in"),
                    ("Stock update", "Stock update"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                    ("write off", "write off"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="defectiveproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
    ]
