# Generated by Django 5.0.6 on 2024-06-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_stocknotifications_transfer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocknotifications",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.transfer",
            ),
        ),
    ]
