# Generated by Django 4.2.16 on 2024-09-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_batchcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="batch_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.batchcode"
            ),
        ),
    ]
