# Generated by Django 5.0.6 on 2024-07-31 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_logo'),
        ('inventory', '0004_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
    ]
