# Generated by Django 4.2.6 on 2024-05-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_transfer_declined_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
