# Generated by Django 4.2.16 on 2024-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_product_batch_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
