# Generated by Django 5.0.6 on 2024-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_reoderlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="reorder",
            field=models.BooleanField(default=False),
        ),
    ]
