# Generated by Django 5.0.6 on 2024-06-29 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_transfer_user_transferitems_received_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
