# Generated by Django 5.0.6 on 2024-06-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_transfer_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transfer",
            name="transfer_status",
            field=models.BooleanField(default=False),
        ),
    ]
