# Generated by Django 5.0.6 on 2024-08-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseorder_discount_purchaseorder_handling_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
