# Generated by Django 4.2.6 on 2024-05-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_activitylog_quantity_alter_activitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "sale"),
                    ("declined", "Declined"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="timestamp",
            field=models.DateField(auto_now_add=True),
        ),
    ]
