# Generated by Django 4.2.6 on 2024-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_activitylog_action_alter_activitylog_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="total_quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
