# Generated by Django 5.0.6 on 2024-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_activitylog_total_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
