# Generated by Django 5.0.6 on 2024-06-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_rename_transfer_status_transfer_defective_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="quantity",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
