# Generated by Django 4.2.16 on 2024-09-25 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_otherexpenses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="handling_amount",
        ),
    ]
