# Generated by Django 5.0.6 on 2024-08-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorder_is_partial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
