# Generated by Django 5.0.6 on 2024-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_transfer_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="total_quantity_track",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
