# Generated by Django 5.0.6 on 2024-05-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_inventory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("exempted", "Exempted"),
                    ("standard", "Standard"),
                    ("zero rated", "Zero Rated"),
                ],
                default="Standard",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
