# Generated by Django 4.2.16 on 2024-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_remove_purchaseorder_handling_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
