# Generated by Django 5.0.6 on 2024-05-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_product_tax_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                ],
                max_length=20,
            ),
        ),
    ]
