# Generated by Django 5.0.6 on 2024-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_transfer_total_quantity_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="quantity_track",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
