# Generated by Django 5.0.6 on 2024-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="batch_code",
            field=models.CharField(default="batch 1", max_length=255),
            preserve_default=False,
        ),
    ]
