# Generated by Django 5.0.6 on 2024-07-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_transferitems_quantity_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferitems",
            name="quantity_track",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
