# Generated by Django 5.0.6 on 2024-05-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_product_batch_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
