# Generated by Django 4.2.16 on 2024-09-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_purchaseorderitem_expected_profit"),
    ]

    operations = [
        migrations.CreateModel(
            name="reorder_settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=255)),
                ("quantity_suggestion", models.BooleanField(default=False)),
                ("number_of_days_from", models.FloatField(null=True)),
                ("number_of_days_to", models.FloatField(null=True)),
                ("order_enough_stock", models.BooleanField(default=False)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorderitem",
                    ),
                ),
            ],
        ),
    ]
