# Generated by Django 5.0.6 on 2024-07-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_transferitems_quantity_track"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitems",
            name="action_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="over_less_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
