# Generated by Django 5.0.6 on 2024-05-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_alter_transfer_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
