# Generated by Django 5.0.6 on 2024-07-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("inventory", "0013_transferitems_action_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectiveproduct",
            name="branch_loss",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loss",
                to="company.branch",
            ),
            preserve_default=False,
        ),
    ]
