# Generated by Django 4.2.16 on 2024-09-30 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_reorder_settings_productdetail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="reorder_settings",
            new_name="reorderSettings",
        ),
    ]
