# Generated by Django 5.0.6 on 2024-07-03 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("inventory", "0014_defectiveproduct_branch_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="reoderlist",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "stock in"),
                    ("Stock update", "Stock update"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                    ("write off", "write off"),
                    ("defective", "defective"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="defectiveproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("lost in transit", "Lost in transit"),
                    ("stolen", "stolen"),
                    ("damaged", "Damage"),
                ],
                max_length=50,
            ),
        ),
    ]
