# Generated by Django 5.0.6 on 2024-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_inventory_quantity_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="total_quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="defectiveproduct",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
