# Generated by Django 4.2.16 on 2024-10-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_product_batch_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="dealer_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
