# Generated by Django 5.0.6 on 2024-05-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0050_alter_customer_phone_number"),
        ("inventory", "0015_alter_activitylog_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="product_transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.transfer",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "Stock in"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                    ("Stock adj", "Stock adj"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
