# Generated by Django 5.0.6 on 2024-07-04 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("inventory", "0015_reoderlist_branch_alter_activitylog_action_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReoderList",
            new_name="ReorderList",
        ),
    ]
