# Generated by Django 5.0.6 on 2024-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_rename_reoderlist_reorderlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "stock in"),
                    ("Stock update", "Stock update"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                    ("write off", "write off"),
                    ("defective", "defective"),
                    ("activated", "activated"),
                    ("deactivated", "deactivated"),
                ],
                max_length=20,
            ),
        ),
    ]
