# Generated by Django 5.0.6 on 2024-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_activitylog_invoice_activitylog_product_transfer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="transfer_ref",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
