# Generated by Django 4.2.16 on 2024-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_inventory_dealer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dealer_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
