# Generated by Django 5.0.6 on 2024-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_transfer_transfer_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_stock_level",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "Stock in"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "Returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                ],
                max_length=20,
            ),
        ),
    ]
