# Generated by Django 4.2.16 on 2024-10-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_costallocationpurchaseorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocationpurchaseorder",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
