# Generated by Django 5.0.6 on 2024-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_product_min_stock_level_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="stock_level_threshold",
            field=models.IntegerField(default=5),
        ),
    ]
