# Generated by Django 4.2.16 on 2024-10-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_alter_costallocationpurchaseorder_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="batch",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
