# Generated by Django 5.0.6 on 2024-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_service_cost_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tax_type',
            field=models.CharField(choices=[('exempted', 'Exempted'), ('standard', 'Standard'), ('zero rated', 'Zero Rated')], default='standard', max_length=50),
            preserve_default=False,
        ),
    ]
