# Generated by Django 5.0.6 on 2024-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_stocknotifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknotifications",
            name="type",
            field=models.CharField(
                choices=[("stock level", "Stock level"), ("stock take", "stock take")],
                default="Stock level",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
