# Generated by Django 5.0.6 on 2024-07-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_service_description_service_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
