# Generated by Django 4.2.16 on 2024-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_remove_product_batch_code_product_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ordered", "Ordered"),
                    ("received", "Received"),
                    ("canceled", "Canceled"),
                ],
                default="received",
                max_length=50,
            ),
        ),
    ]
