# Generated by Django 4.2.16 on 2024-10-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0024_alter_product_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="batch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
