# Generated by Django 5.0.6 on 2024-07-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitems',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
