# Generated by Django 5.0.6 on 2024-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_transferitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknotifications',
            name='quanity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
