# Generated by Django 4.2.16 on 2024-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_alter_product_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="batch",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
