# Generated by Django 5.0.6 on 2024-07-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_stocknotifications_quanity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
