# Generated by Django 4.2.16 on 2024-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0026_inventory_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="batch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="dealer_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="reorder",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="status",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="stock_level_threshold",
            field=models.IntegerField(default=5, null=True),
        ),
    ]
