# Generated by Django 5.0.6 on 2024-07-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_activitylog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocknotifications',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
