# Generated by Django 4.2.16 on 2024-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0027_inventory_name_alter_inventory_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="dealer_expected_profit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
