# Generated by Django 5.0.6 on 2024-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_rename_quanity_stocknotifications_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderlist',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reorderlist',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
