# Generated by Django 5.0.6 on 2024-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_reorderlist_cost_reorderlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorderlist',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
