# Generated by Django 4.2.16 on 2024-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0029_purchaseorder_hold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="end_of_day",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="service",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("exempted", "Exempted"),
                    ("standard", "Standard"),
                    ("zero rated", "Zero Rated"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
