# Generated by Django 4.2.16 on 2024-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0030_alter_product_cost_alter_product_end_of_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="system_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
