# Generated by Django 5.0.6 on 2024-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_reorderlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_notification',
            field=models.BooleanField(default=False),
        ),
    ]
