# Generated by Django 4.2.16 on 2024-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0032_alter_activitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("stock in", "stock in"),
                    ("Stock update", "Stock update"),
                    ("stock adjustment", "stock adjustment"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("edit", "Edit"),
                    ("transfer", "Transfer"),
                    ("returns", "returns"),
                    ("sale", "Sale"),
                    ("declined", "Declined"),
                    ("write off", "write off"),
                    ("defective", "defective"),
                    ("activated", "activated"),
                    ("deactivated", "deactivated"),
                    ("removed", "removed"),
                    ("purchase edit", "purchase edit"),
                ],
                max_length=20,
            ),
        ),
    ]
