# Generated by Django 5.0.6 on 2024-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_product_alert_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alert_notification',
        ),
        migrations.AddField(
            model_name='inventory',
            name='alert_notification',
            field=models.BooleanField(default=False),
        ),
    ]
