# Generated by Django 5.0.6 on 2024-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='alert_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
