# Generated by Django 5.0.6 on 2024-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.CharField>/logo/'),
        ),
    ]
