# Generated by Django 5.0.6 on 2024-05-19 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
    ]
