# Generated by Django 5.0.6 on 2024-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_remove_company_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
