# Generated by Django 5.0.6 on 2024-06-03 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_branch_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="description",
        ),
    ]
