# Generated by Django 5.0.6 on 2024-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_remove_branch_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
